README.md
=> docs(readme): add description to README.md

README.md
Added personal page links and group members photo.
=> docs(readme): add group pictures and personal page link

README.md
Navigation guide added.Logo is the center of the page now.Some format changes done.
=> docs(readme): added navigation guide and some changes about format

README.md
=>  docs(readme): added social Actopus gif

ApiDesign/twitter/controllers/geo.js, ApiDesign/twitter/controllers/index.js, ApiDesign/twitter/modules/geo.js, ApiDesign/twitter/modules/index.js, ApiDesign/webProject/src/app/app.component.html, ApiDesign/webProject/src/app/app.component.ts, ApiDesign/webProject/src/app/services/backend-service.service.ts
I added the work of Gökhan on geo/search which we have missed before
=> geo/search endpoint is added, work of Gökhan

backend/Readme.md, frontend/Readme.md
@kemaltulum Could you add the frontend folder Kemal. And then confirm the merge also?
=> Backend folder is added

README.md
kemal added contribution.md file, I thought the file is too long for readme, so I am putting the link of the file to the readme.
=> add contributing link to readme

backend/controllers/UserController.js, backend/routes/auth.js
The sign in page created and it checks the user already sign up or not
=> f-signin first interim 

backend/app.js, backend/controllers/UserController.js, backend/models/User.js, backend/package.json, backend/routes/auth.js
There is the last version of the sign in.I made hashing our password with the express-session.
=> F signin- last version 

frontend/src/app/auth/pages/signup/signup.page.html, frontend/src/app/auth/pages/signup/signup.page.ts, frontend/src/app/auth/providers/auth/auth.service.ts
This PR synchronizes frontend and backend endpoints and data fields.
=> Synchronize Frontend-Backend

backend/.gitignore, backend/app.js, frontend/package.json, frontend/src/app/auth/providers/auth/auth.service.ts
This PR resolves the backend-frontend synchronization issues such as unstable routing, detected by @nazmicancalik, @kemaltulum and @okyksl.
=> Serve Frontend Correctly

backend/app.js
Deleted the extra http server. Fix for heroku deployment.
=> Heroku deploy fix

backend/controllers/AuthController.js, frontend/src/app/auth/auth-routing.module.ts, frontend/src/app/auth/auth.module.ts, frontend/src/app/auth/guards/auth/auth.guard.spec.ts, frontend/src/app/auth/guards/auth/auth.guard.ts, frontend/src/app/auth/guards/no-auth/no-auth.guard.spec.ts, frontend/src/app/auth/guards/no-auth/no-auth.guard.ts, frontend/src/app/auth/pages/signin/signin.page.ts, frontend/src/app/auth/pages/signup/signup.page.ts, frontend/src/app/auth/providers/auth/auth.service.ts, frontend/src/app/events/event-routing.module.ts, frontend/src/app/events/pages/event-create/event-create.page.ts, frontend/src/app/events/pages/feed/feed.page.html, frontend/src/app/events/pages/feed/feed.page.scss, frontend/src/app/events/pages/feed/feed.page.ts, package-lock.json, package.json
This PR adds guards to the specific frontend routes based on authentication. Additionally, automatic redirect and automatic sign-in is added. PR also adds **expiration date for the JWT token returned from the backend side**. Closes #238.
=> Auth Guards & Routing

frontend/README.md
Fix broken script detected by @serkan-ozel-2015400123.
=> docs(dev): correct local development script

backend/app.js, backend/controllers/EventController.js, backend/controllers/UserController.js
=> Converted to global promises when using mongoose

backend/controllers/EventController.js
fixed missing map function argument
=> added missing collection to map

backend/models/User.js
Added follower, following interests to the user data model
=> Added follower,following,interests to the user data model

backend/controllers/EventController.js, backend/routes/events.js
=> Added update/add/get attendance endpoints.

frontend/src/app/auth/pages/signup/signup.page.ts, frontend/src/app/auth/providers/auth/auth.service.ts, frontend/src/app/interfaces/user.interface.ts
User model adjusted according to backend model.
Auth service register, sign up page data sending, getUser renamed to getUserId in auth.
=> refactor(user model and auth): refactor user models according to backend

backend/controllers/EventController.js, backend/routes/events.js
I merged the **delete event** functionality with the `master`. Closes #180.
=> Delete Event Functionality

backend/.eslintrc.json, backend/models/User.js, backend/package.json
* Adds **airbnb linting** to the project. This also lints _whole user data model_.
* Quickfix to assure that we check `name` field is required.
=> Fix: Require User Name

.circleci/config.yml, frontend/package.json, scripts/deploy.sh
Adds **automatic testing in PRs** and **automatic deploy from master** branch. Closes #177.
=> CircleCI Integration

backend/bin/www, backend/package.json, scripts/deploy.sh
I changed the port to 80, notice that this doesn't resolve the whole issue, I gave node access to port 80 by running the following commands by hand in the Digital Ocean machine:
sudo apt-get install libcap2-bin
sudo setcap cap_net_bind_service=+ep /usr/bin/node
Also, notice that this configuration will not effect the remote server before we merge #345 :)
=> Changed default port no to 80

backend/app.js, backend/controllers/EventController.js
While testing for attendance endpoints, I noticed the GET endpoint doesn't work because of a simple bug. We can surely merge this one line change because I already tested it :)
=> Minor fix for attendance testing

frontend/src/app/interfaces/user.interface.ts
Quick fix to resolve deploy problem.
=> fix(interfaces): make fields of user optional

.circleci/config.yml, scripts/deploy.sh
Adds a build task which will be a necessary check for each PR. Closes #298.
=> Build CI Task

.circleci/config.yml, scripts/deploy.sh
Handles dev & production CD issues.
=> Fix CI & CD

backend/app.js, backend/controllers/EventController.js, backend/controllers/UserController.js, backend/models/Event.js, backend/models/Media.js, backend/models/User.js, backend/routes/events.js, backend/routes/users.js, frontend/src/app/interfaces/event.interface.ts, frontend/src/app/interfaces/media.interface.ts
Thanks to @nazmicancalik for his work on CommentsSchema which was essentially the work needed to solve the multimedia data model issue.
I integrated what he did to media objects and it seems to work  fine.
=========== UPDATE ============
I have worked further on medias and as of now:
- We have a seperate file models/Media.js which includes MediaSchema shared by both Event objects and User objects
- User endpoints have "media" field instead of "images" with the following structure:
media:
{
avatar: MediaSchema,
cover: MediaSchema
}
- GET, POST, PUT and DELETE endpoints are implemented for avatar and cover:
GET /api/users/:id/avatar
DELETE /api/users/:id/cover
etc.
=> Multimedia Endpoints and Data Model Finalization 

frontend/src/global.scss
Just like we talked at meeting :).
Closes #374.
=> fix(ion-item): make borders transparent

frontend/src/app/annotation/annotation-directive/annotation.directive.ts, frontend/src/app/annotation/components/annotated-body/annotated-body.component.ts, frontend/src/app/events/pages/event/event.page.html, frontend/src/app/events/pages/event/event.page.ts
Timeout fix between event detail page and directive. 
console.logs deleted
Two prices for small and large screens made annotatable (shared)
=> fix(): several fixes

frontend/src/app/annotation/annotation-directive/annotation.directive.ts, frontend/src/app/events/pages/event/event.page.html, frontend/src/app/events/pages/event/event.page.scss, frontend/src/app/events/pages/event/event.page.ts
Annotation button added 
Only show annotation options when annotation mode is opened
=> refactor(annotate): toggle annotate button

backend/controllers/SearchController.js, frontend/package-lock.json, frontend/src/app/auth/pages/signin/signin.page.ts, frontend/src/app/events/pages/event-create/event-create.page.ts, frontend/src/app/events/pages/event/event.page.ts, frontend/src/app/profile/pages/public/public.page.ts, frontend/src/app/profile/pages/settings/settings.page.ts
=> Guest Redirect Fix

frontend/README.md, frontend/resources/data/events/event1.json, frontend/src/app/annotation/components/annotated-body/annotated-body.component.ts, frontend/src/app/auth/providers/auth/auth.service.spec.ts, frontend/src/app/auth/providers/auth/auth.service.ts
This PR adds **unit tests** for `AuthService`.
=> Unit Tests for Auth Service
